# Generated by Django 5.2 on 2025-04-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sale_saleitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reorder_level',
            new_name='low_stock_threshold',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
