# Generated by Django 5.2 on 2025-04-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_order_date_purchaseorder_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
